#pragma once


#define SOCKETDEVICE_OPERATION_SUCCEEDED                 0	// WIN PB
#define SOCKETDEVICE_FUNCTION_UNSUPPORTED                1	// WIN PB
#define SOCKETDEVICE_INVALID_PARAMETER_FOUND             2	// WIN PB
#define SOCKETDEVICE_OPERATION_FAILED                    3	// WIN PB
#define SOCKETDEVICE_CHAR_FONT_PATTERN_RETRIEVE_FAILURE  4	//     PB
#define SOCKETDEVICE_ALREADY_OPENED                      5	// WIN PB
#define SOCKETDEVICE_NOT_OPENED                          6	// WIN PB
#define SOCKETDEVICE_DEVICE_TYPE_UNSUPPORTED             7	//     PB
#define SOCKETDEVICE_OPERATION_UNSUPPORTED               8	// WIN PB
#define SOCKETDEVICE_EOJ_RECEIVE_FAILURE                 9	//     PB PSC_EOJ_RECEIVE_FAILURE
#define SOCKETDEVICE_INVALID_PRINT_DATA_FOUND            10	// WIN PB
#define SOCKETDEVICE_OPERATION_CANCELED                  11	// WIN PB
#define SOCKETDEVICE_INSUFFICIENT_MEMORY                 12	// WIN PB
#define SOCKETDEVICE_OPERATION_TIMED_OUT                 13	//     PB PSC_OPERATION_TIMEOUT
#define SOCKETDEVICE_SOCKET_IS_GOING_TO_AFK              14	// WIN
#define SOCKETDEVICE_PORTRAIT_SETTING_ERROR              15	// WIN
#define SOCKETDEVICE_PAPER_DIMENSIONS_SETTING_ERROR      16	// WIN
#define SOCKETDEVICE_PAPER_SOURCE_SPECIFYING_ERROR       17	// WIN
#define SOCKETDEVICE_ANOTHER_OPEN_IN_PROGRESS            19
#define SOCKETDEVICE_NO_MS_READ_REQUEST_ISSUED           20	//     PB PSC_NO_MS_READ_REQUEST_ISSUED
#define SOCKETDEVICE_MS_READ_REQUEST_FAILURE             21	//     PB PSC_MS_READ_REQUEST_FAILURE
#define SOCKETDEVICE_MS_DATA_FRAME_RECEIVE_FAILURE       22	//     PB PSC_MS_DATA_FRAME_RECEIVE_FAILURE
#define SOCKETDEVICE_READ_BUFFER_TOO_SHORT               23	// WIN PB
#define SOCKETDEVICE_NO_MS_WRITE_REQUEST_ISSUED          30	//     PB
#define SOCKETDEVICE_MS_WRITE_REQUEST_FAILURE            31	//     PB PSC_MS_WRITE_REQUEST_FAILURE
#define SOCKETDEVICE_MS_IO_REQUEST_PENDING_COMPLETION    40	//     PB
#define SOCKETDEVICE_MS_IO_REQUEST_DATA_FRAME_TX_FAILURE 41	//     PB PSC_MS_IO_REQUEST_DATA_FRAME_TX_FAILURE
#define SOCKETDEVICE_FILE_NOT_FOUND                      50	// WIN
#define SOCKETDEVICE_FAILED_TO_GET_FILE_SIZE             51	// WIN
#define SOCKETDEVICE_FAILED_TO_OPEN_FILE                 52	// WIN
#define SOCKETDEVICE_FAILED_TO_READ_FILE                 53	// WIN
#define SOCKETDEVICE_INSUFFICIENT_DATA_READ_FROM_FILE    54	// WIN
#define SOCKETDEVICE_JOB_IS_PRINTING_IN_QUEUE            55  // WIN
#define SOCKETDEVICE_JOB_ERROR_IN_QUEUE                  56  // WIN
#define GDIPRINTER_NO_MORE_RESOURCE                    101
